### ISSUE TITLE
Double enemy ship spawn

### ISSUE THREAD

**Issue by Cruzzador** [JSJBDEV/pirates#25]
Enemy ships spawn double upon each other

Game version 1.20.1 
Mod version 1.4.2 ValkyrienPirates-1.4.3.jar

[2025-02-23-4.log.gz](https://github.com/user-attachments/files/18947874/2025-02-23-4.log.gz)
[2025-02-23-3.log.gz](https://github.com/user-attachments/files/18947875/2025-02-23-3.log.gz)

**Comment by Illuminat10n** [comment]
Can confirm, still a problem on 1.8.1

**Comment by JSJBDEV** [comment]
this is fixed in the newest version of vlib (not on modrinth yet) it is not a pirates issue

**Comment by techheadfred-git** [comment]
Unfortunately I'm still seeing this sometimes even with latest VS2 and vlib.
It is less common, though!

Is it worth tracking on the vlib GitHub, or is this a VS issue?

**Comment by ackbarscrowbars** [comment]
Just encountered this, still an issue in v1.9.2

**Comment by JSJBDEV** [comment]
I'm going to close this issue here as we are pretty certain it's a vlib issue not a pirates one, but yeah I think it's reduced but not perfect unfortunately
